export function buildAdminPage() {

  var css = [
    ':root{--bg:#0d1117;--bg2:#161b22;--bg3:#21262d;--bg4:#30363d;--accent:#58a6ff;--accent2:#1f6feb;--green:#3fb950;--red:#f85149;--yellow:#d29922;--text:#c9d1d9;--text2:#8b949e;--text3:#484f58;--radius:8px}',
    '*{box-sizing:border-box;margin:0;padding:0}',
    'body{font-family:-apple-system,system-ui,sans-serif;background:var(--bg);color:var(--text);min-height:100vh}',
    '.header{background:var(--bg2);border-bottom:1px solid var(--bg4);padding:1rem 2rem;display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:1rem}',
    '.header h1{font-size:1.4rem;color:var(--accent)}',
    '.header .info{font-size:.8rem;color:var(--text2);background:var(--bg);padding:4px 12px;border-radius:20px;border:1px solid var(--bg4)}',
    '.nav{display:flex;background:var(--bg2);border-bottom:1px solid var(--bg4);overflow-x:auto}',
    '.nav button{background:none;border:none;color:var(--text2);padding:12px 24px;cursor:pointer;font-size:.9rem;border-bottom:2px solid transparent;white-space:nowrap;transition:all .2s}',
    '.nav button:hover{color:var(--text)}',
    '.nav button.active{color:var(--accent);border-bottom-color:var(--accent)}',
    '.container{max-width:960px;margin:0 auto;padding:2rem 1rem}',
    '.page{display:none}.page.active{display:block}',
    '.login-box{max-width:360px;margin:4rem auto;text-align:center}',
    '.login-box h2{color:var(--accent);margin-bottom:1rem}',
    '.login-box p{color:var(--text2);margin-bottom:1.5rem;font-size:.9rem}',
    'input,textarea{background:var(--bg);color:var(--text);border:1px solid var(--bg4);padding:12px;border-radius:var(--radius);width:100%;margin-bottom:12px;font-family:monospace;font-size:.9rem}',
    'input:focus,textarea:focus{outline:none;border-color:var(--accent)}',
    '.btn{padding:8px 16px;border-radius:var(--radius);border:none;cursor:pointer;font-size:.85rem;font-weight:600;transition:all .2s;display:inline-block;margin:3px}',
    '.btn:hover{transform:translateY(-1px)}',
    '.btn-primary{background:var(--green);color:#fff}',
    '.btn-blue{background:var(--accent);color:#fff}',
    '.btn-secondary{background:var(--bg4);color:var(--text)}',
    '.btn-danger{background:var(--red);color:#fff}',
    '.btn-warn{background:var(--yellow);color:#000}',
    '.btn-sm{padding:4px 10px;font-size:.75rem}',
    '.card{background:var(--bg2);border:1px solid var(--bg4);border-radius:10px;padding:1.2rem;margin-bottom:12px}',
    '.stitle{color:var(--text2);font-size:.8rem;text-transform:uppercase;letter-spacing:1px;margin:1.5rem 0 1rem;padding-bottom:.5rem;border-bottom:1px solid var(--bg4)}',
    '.stats-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px;margin-bottom:1.5rem}',
    '.stat-card{background:var(--bg2);border:1px solid var(--bg4);border-radius:10px;padding:1rem;text-align:center}',
    '.stat-card .num{font-size:1.8rem;font-weight:700;color:var(--accent)}',
    '.stat-card .label{font-size:.7rem;color:var(--text2);margin-top:4px;text-transform:uppercase}',
    'table{width:100%;border-collapse:collapse;font-size:.85rem}',
    'th{text-align:left;padding:10px 12px;color:var(--text3);border-bottom:1px solid var(--bg4);font-size:.7rem;text-transform:uppercase;letter-spacing:.5px}',
    'td{padding:10px 12px;border-bottom:1px solid var(--bg3);vertical-align:middle}',
    'tr:hover td{background:rgba(255,255,255,.015)}',
    '.badge{display:inline-block;padding:3px 10px;border-radius:12px;font-size:.7rem;font-weight:600}',
    '.badge-green{background:rgba(63,185,80,.12);color:var(--green)}',
    '.badge-red{background:rgba(248,81,73,.12);color:var(--red)}',
    '.badge-blue{background:rgba(88,166,255,.1);color:var(--accent)}',
    '.mono{font-family:monospace;font-size:.8rem;color:var(--yellow)}',
    '.actions{display:flex;gap:4px;flex-wrap:wrap}',
    '.info-box{background:var(--bg);border:1px solid var(--bg4);border-radius:var(--radius);padding:10px 14px;font-family:monospace;font-size:.85rem;color:var(--yellow);margin-bottom:10px;word-break:break-all}',
    '.help-text{color:var(--text3);font-size:.8rem;margin-top:8px;line-height:1.6}',
    '.help-text code{background:var(--bg);padding:2px 6px;border-radius:4px;color:var(--yellow);font-size:.75rem}',
    '.row{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}',
    '.toast{position:fixed;bottom:20px;right:20px;padding:12px 24px;border-radius:var(--radius);color:#fff;font-weight:600;z-index:9999;display:none;box-shadow:0 4px 20px rgba(0,0,0,.4)}',
    '.twrap{overflow-x:auto}',
    '@media(max-width:768px){.stats-grid{grid-template-columns:repeat(2,1fr)}}',
  ].join('\n');

  var body = [
    '<div class="header"><h1>&#9889; MiMo2API</h1><span class="info" id="hInfo">Not logged in</span></div>',
    '<div class="nav" id="navBar">',
    '<button onclick="sp(\'login\')" id="nav-login" class="active">Login</button>',
    '</div>',
    '<div class="container">',

    // Login
    '<div class="page active" id="page-login"><div class="login-box">',
    '<h2>&#128274; MiMo2API</h2><p>Reverse Proxy Admin Panel</p>',
    '<input type="password" id="pwdInput" placeholder="Admin password">',
    '<button class="btn btn-blue" onclick="doLogin()" style="width:100%;padding:14px;font-size:1rem">Authenticate</button>',
    '<div id="loginErr" style="color:var(--red);font-size:.85rem;margin-top:8px;min-height:18px"></div>',
    '</div></div>',

    // Dashboard
    '<div class="page" id="page-dashboard">',
    '<div class="stitle">Overview</div>',
    '<div class="stats-grid" id="statsGrid"></div>',
    '<div class="card">',
    '<div class="stitle" style="margin-top:0">Connection Info</div>',
    '<div class="info-box" id="infoBase"></div>',
    '<div class="info-box">GET /v1/models</div>',
    '<div class="info-box">POST /v1/chat/completions</div>',
    '</div>',
    '<div class="card">',
    '<div class="stitle" style="margin-top:0">Directives</div>',
    '<p class="help-text">Add in any system message. Last directive wins.<br><br>',
    '<code>[think=on]</code> / <code>[think=off]</code> &#8212; Chain-of-thought<br>',
    '<code>[search=on]</code> / <code>[search=off]</code> &#8212; Web search<br>',
    '<code>[resend=true]</code> &#8212; Resend system prompt every message<br><br>',
    'Any model ID sent by the client is passed through to MiMo regardless.</p>',
    '</div>',
    '</div>',

    // Accounts
    '<div class="page" id="page-accounts">',
    '<div class="stitle">Add Account (Paste cURL)</div>',
    '<div class="card">',
    '<input type="text" id="accLabel" placeholder="Label (e.g. Main Account)">',
    '<textarea id="accCurl" rows="4" placeholder="Paste the full cURL from browser DevTools..."></textarea>',
    '<button class="btn btn-primary" onclick="addAccount()">Add Account</button>',
    '<p class="help-text">DevTools &gt; Network &gt; find chat request &gt; Copy as cURL</p>',
    '</div>',
    '<div class="stitle">Auto-Login via CDP (no cURL needed)</div>',
    '<div class="card">',
    '<p class="help-text">Drives a headless chromium via CDP to log in for you. Phase 1 starts the flow and emails a 6-digit code; Phase 2 submits the code and stores the cookies. Requires chromium on PATH or already running on port 9333.</p>',
    '<input type="text" id="alEmail" placeholder="Xiaomi account email">',
    '<input type="password" id="alPass" placeholder="Xiaomi account password">',
    '<div class="row">',
    '<input type="text" id="alCode" placeholder="6-digit email code (Phase 2 only)" style="flex:1">',
    '<button class="btn btn-blue" onclick="autoLoginStart()">Phase 1: Start</button>',
    '<button class="btn btn-primary" onclick="autoLoginComplete()">Phase 2: Complete</button>',
    '</div>',
    '<div id="alStatus" class="info-box" style="display:none"></div>',
    '</div>',
    '<div class="stitle">Account List</div>',
    '<div class="card"><div class="twrap"><table>',
    '<thead><tr><th>Label</th><th>User ID</th><th>Status</th><th>Requests</th><th>Last Used</th><th>Actions</th></tr></thead>',
    '<tbody id="accTbl"></tbody>',
    '</table></div></div>',
    '</div>',

    // API Keys
    '<div class="page" id="page-keys">',
    '<div class="stitle">Generate Key</div>',
    '<div class="card">',
    '<div class="row">',
    '<input type="text" id="keyName" placeholder="Key name (e.g. SillyTavern)" style="flex:1">',
    '<button class="btn btn-blue" onclick="createKey()">Generate</button>',
    '</div></div>',
    '<div class="stitle">Key List</div>',
    '<div class="card"><div class="twrap"><table>',
    '<thead><tr><th>Name</th><th>Key</th><th>Status</th><th>Requests</th><th>Created</th><th>Actions</th></tr></thead>',
    '<tbody id="keyTbl"></tbody>',
    '</table></div></div>',
    '</div>',

    // Models
    '<div class="page" id="page-models">',
    '<div class="stitle">Add Model</div>',
    '<div class="card">',
    '<div class="row">',
    '<input type="text" id="mdlId" placeholder="Model ID (e.g. mimo-v2.5-pro)" style="flex:1">',
    '<input type="text" id="mdlName" placeholder="Display name (optional)" style="flex:1">',
    '<button class="btn btn-primary" onclick="addModel()">Add</button>',
    '</div>',
    '<p class="help-text">This populates /v1/models. Client-sent model IDs are always passed through.</p>',
    '</div>',
    '<div class="stitle">Model List</div>',
    '<div class="card"><div class="twrap"><table>',
    '<thead><tr><th>Model ID</th><th>Display Name</th><th>Status</th><th>Actions</th></tr></thead>',
    '<tbody id="mdlTbl"></tbody>',
    '</table></div></div>',
    '</div>',

    // Sessions
    '<div class="page" id="page-sessions">',
    '<div class="stitle" style="display:flex;justify-content:space-between;align-items:center">',
    '<span>Active Sessions</span>',
    '<button class="btn btn-warn btn-sm" onclick="clearConvs()">Clear All</button>',
    '</div>',
    '<div class="card"><div class="twrap"><table>',
    '<thead><tr><th>Session</th><th>Account</th><th>Model</th><th>Msgs</th><th>Last Active</th><th>Created</th></tr></thead>',
    '<tbody id="sessTbl"></tbody>',
    '</table></div></div>',
    '</div>',

    '</div>',
    '<div class="toast" id="toast"></div>',
  ].join('\n');

  var js = [
    'var token=localStorage.getItem("m2a_token")||"";',
    'var loggedIn=false;',
    '',
    'function sp(n){',
    '  if(["dashboard","accounts","keys","models","sessions"].indexOf(n)!==-1&&!loggedIn){sp("login");toast("Login first","#f85149");return;}',
    '  var ps=document.querySelectorAll(".page"),bs=document.querySelectorAll(".nav button");',
    '  for(var i=0;i<ps.length;i++)ps[i].classList.remove("active");',
    '  for(var i=0;i<bs.length;i++)bs[i].classList.remove("active");',
    '  var p=document.getElementById("page-"+n),b=document.getElementById("nav-"+n);',
    '  if(p)p.classList.add("active");if(b)b.classList.add("active");',
    '  if(n==="dashboard")loadDash();',
    '  if(n==="accounts")loadAccounts();',
    '  if(n==="keys")loadKeys();',
    '  if(n==="models")loadModels();',
    '  if(n==="sessions")loadSessions();',
    '}',
    '',
    'function hdr(){return{"Authorization":"Bearer "+token,"Content-Type":"application/json"};}',
    '',
    'function api(path,opts){',
    '  opts=opts||{};',
    '  opts.headers=hdr();',
    '  return fetch(path,opts).then(function(r){',
    '    return r.json().then(function(d){',
    '      if(!r.ok)throw new Error(d.error||"Request failed");',
    '      return d;',
    '    });',
    '  });',
    '}',
    '',
    'function toast(m,c){var t=document.getElementById("toast");t.textContent=m;t.style.background=c||"#3fb950";t.style.display="block";setTimeout(function(){t.style.display="none";},3000);}',
    '',
    'function esc(s){var d=document.createElement("div");d.textContent=s;return d.innerHTML;}',
    '',
    'function maskKey(k){return k.slice(0,14)+"\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022\\u2022"+k.slice(-4);}',
    '',
    'function timeAgo(d){',
    '  if(!d)return"\\u2014";',
    '  var s=Math.floor((Date.now()-new Date(d+"Z").getTime())/1000);',
    '  if(s<60)return s+"s ago";',
    '  if(s<3600)return Math.floor(s/60)+"m ago";',
    '  if(s<86400)return Math.floor(s/3600)+"h ago";',
    '  return Math.floor(s/86400)+"d ago";',
    '}',
    '',
    'function cp(text){navigator.clipboard.writeText(text).then(function(){toast("Copied!","#3fb950");}).catch(function(){toast("Copy failed","#f85149");});}',
    '',
    '// ── Auth ──',
    'function doLogin(){',
    '  var pw=document.getElementById("pwdInput").value;',
    '  if(!pw){toast("Enter password","#f85149");return;}',
    '  fetch("/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:pw})})',
    '  .then(function(r){return r.json().then(function(d){if(!r.ok)throw new Error(d.error);return d;});})',
    '  .then(function(d){',
    '    token=d.token;loggedIn=true;localStorage.setItem("m2a_token",token);',
    '    document.getElementById("hInfo").textContent="Admin";',
    '    document.getElementById("hInfo").style.borderColor="#3fb950";',
    '    buildNav();sp("dashboard");toast("Logged in!","#3fb950");',
    '  }).catch(function(e){document.getElementById("loginErr").textContent=e.message;token="";localStorage.removeItem("m2a_token");});',
    '}',
    '',
    'function logout(){token="";loggedIn=false;localStorage.removeItem("m2a_token");location.reload();}',
    '',
    'function buildNav(){',
    '  var nav=document.getElementById("navBar");nav.innerHTML="";',
    '  var tabs=[["dashboard","Dashboard"],["accounts","Accounts"],["keys","API Keys"],["models","Models"],["sessions","Sessions"]];',
    '  for(var i=0;i<tabs.length;i++){',
    '    var btn=document.createElement("button");',
    '    btn.id="nav-"+tabs[i][0];',
    '    btn.textContent=tabs[i][1];',
    '    btn.setAttribute("data-p",tabs[i][0]);',
    '    btn.onclick=function(){sp(this.getAttribute("data-p"));};',
    '    nav.appendChild(btn);',
    '  }',
    '  var lbtn=document.createElement("button");lbtn.textContent="Logout";lbtn.onclick=logout;nav.appendChild(lbtn);',
    '}',
    '',
    'document.getElementById("pwdInput").addEventListener("keydown",function(e){if(e.key==="Enter")doLogin();});',
    '',
    '// ── Dashboard ──',
    'function loadDash(){',
    '  document.getElementById("infoBase").textContent=location.origin+"/v1";',
    '  var sg=document.getElementById("statsGrid");',
    '  var p1=api("/admin/accounts").catch(function(){return[];});',
    '  var p2=api("/admin/keys").catch(function(){return[];});',
    '  var p3=api("/admin/models").catch(function(){return[];});',
    '  var p4=api("/admin/conversations").catch(function(){return[];});',
    '  Promise.all([p1,p2,p3,p4]).then(function(res){',
    '    var accs=res[0]||[];var keys=res[1]||[];var mdls=res[2]||[];var convs=res[3]||[];',
    '    var activeAccs=accs.filter(function(r){return r.active;}).length;',
    '    var activeKeys=keys.filter(function(r){return r.active;}).length;',
    '    var activeMdls=mdls.filter(function(r){return r.active;}).length;',
    '    var totalReqs=accs.reduce(function(s,r){return s+(r.request_count||0);},0);',
    '    sg.innerHTML=sc(activeAccs,"Accounts")+sc(activeKeys,"API Keys")+sc(activeMdls,"Models")+sc(totalReqs,"Requests")+sc(convs.length,"Sessions");',
    '  });',
    '}',
    'function sc(v,l){return "<div class=\\"stat-card\\"><div class=\\"num\\">"+v+"</div><div class=\\"label\\">"+l+"</div></div>";}',
    '',
    '// ── Accounts ──',
    'function loadAccounts(){',
    '  api("/admin/accounts").then(function(rows){',
    '    var tb=document.getElementById("accTbl");',
    '    if(!rows.length){tb.innerHTML="<tr><td colspan=\\"6\\" style=\\"text-align:center;color:var(--text3);padding:24px\\">No accounts yet.</td></tr>";return;}',
    '    var h="";',
    '    for(var i=0;i<rows.length;i++){',
    '      var r=rows[i];',
    '      h+="<tr>";',
    '      h+="<td>"+esc(r.label||"\\u2014")+"</td>";',
    '      h+="<td class=\\"mono\\">"+esc(r.user_id)+"</td>";',
    '      h+="<td><span class=\\"badge "+(r.active?"badge-green":"badge-red")+"\\">"+(r.active?"Active":"Off")+"</span></td>";',
    '      h+="<td>"+(r.request_count||0)+"</td>";',
    '      h+="<td style=\\"color:var(--text2)\\">"+(r.last_used?timeAgo(r.last_used):"Never")+"</td>";',
    '      h+="<td class=\\"actions\\">";',
    '      h+="<button class=\\"btn btn-secondary btn-sm\\" onclick=\\"togAcc("+r.id+","+(r.active?0:1)+")\\">"+(r.active?"Disable":"Enable")+"</button>";',
    '      h+="<button class=\\"btn btn-danger btn-sm\\" onclick=\\"delAcc("+r.id+")\\">Del</button>";',
    '      h+="</td></tr>";',
    '    }',
    '    tb.innerHTML=h;',
    '  }).catch(function(e){toast(e.message,"#f85149");});',
    '}',
    '',
    'function addAccount(){',
    '  var curl=document.getElementById("accCurl").value;',
    '  var label=document.getElementById("accLabel").value;',
    '  if(!curl.trim()){toast("Paste a cURL","#f85149");return;}',
    '  api("/admin/accounts",{method:"POST",body:JSON.stringify({curl:curl,label:label})})',
    '  .then(function(){document.getElementById("accCurl").value="";document.getElementById("accLabel").value="";toast("Account added!","#3fb950");loadAccounts();})',
    '  .catch(function(e){toast(e.message,"#f85149");});',
    '}',
    '',
    '// ── Auto-Login (CDP) ──',
    'function alShow(msg,ok){var b=document.getElementById("alStatus");b.style.display="block";b.textContent=msg;b.style.color=ok?"#3fb950":"#d29922";}',
    'function alHide(){document.getElementById("alStatus").style.display="none";}',
    'function autoLoginStart(){',
    '  var em=document.getElementById("alEmail").value,pa=document.getElementById("alPass").value;',
    '  if(!em||!pa){toast("Email + password required","#f85149");return;}',
    '  alShow("Starting browser login (Phase 1)... this may take ~10s",false);',
    '  api("/admin/accounts/autologin",{method:"POST",body:JSON.stringify({email:em,password:pa})})',
    '  .then(function(r){alShow("Phase 1 done. "+(r.message||"")+"  Now paste the 6-digit code from the email and click Phase 2.",true);})',
    '  .catch(function(e){alShow("Phase 1 failed: "+e.message,false);});',
    '}',
    'function autoLoginComplete(){',
    '  var em=document.getElementById("alEmail").value,pa=document.getElementById("alPass").value,co=document.getElementById("alCode").value;',
    '  if(!em||!pa){toast("Email + password required","#f85149");return;}',
    '  if(!co||co.length<4){toast("Enter the 6-digit code","#f85149");return;}',
    '  alShow("Submitting code (Phase 2)... this may take ~30s",false);',
    '  api("/admin/accounts/autologin",{method:"POST",body:JSON.stringify({email:em,password:pa,code:co})})',
    '  .then(function(r){alShow("Account added via auto-login! userId="+(r.userId||"?"),true);document.getElementById("alCode").value="";loadAccounts();})',
    '  .catch(function(e){alShow("Phase 2 failed: "+e.message,false);});',
    '}',
    '',
    'function togAcc(id,active){api("/admin/accounts/"+id,{method:"PATCH",body:JSON.stringify({active:!!active})}).then(function(){loadAccounts();});}',
    '',
    'function delAcc(id){if(!confirm("Delete this account?"))return;api("/admin/accounts/"+id,{method:"DELETE"}).then(function(){toast("Deleted","#3fb950");loadAccounts();loadSessions();});}',
    '',
    '// ── API Keys ──',
    'function loadKeys(){',
    '  api("/admin/keys").then(function(rows){',
    '    var tb=document.getElementById("keyTbl");',
    '    if(!rows.length){tb.innerHTML="<tr><td colspan=\\"6\\" style=\\"text-align:center;color:var(--text3);padding:24px\\">No keys yet.</td></tr>";return;}',
    '    var h="";',
    '    for(var i=0;i<rows.length;i++){',
    '      var r=rows[i];',
    '      h+="<tr>";',
    '      h+="<td>"+esc(r.name||"\\u2014")+"</td>";',
    '      h+="<td class=\\"mono\\" style=\\"cursor:pointer\\" onclick=\\"cp(\'"+esc(r.key)+"\')\\"  >"+maskKey(r.key)+"</td>";',
    '      h+="<td><span class=\\"badge "+(r.active?"badge-green":"badge-red")+"\\">"+(r.active?"Active":"Off")+"</span></td>";',
    '      h+="<td>"+(r.request_count||0)+"</td>";',
    '      h+="<td style=\\"color:var(--text2)\\">"+timeAgo(r.created_at)+"</td>";',
    '      h+="<td class=\\"actions\\">";',
    '      h+="<button class=\\"btn btn-secondary btn-sm\\" onclick=\\"togKey("+r.id+","+(r.active?0:1)+")\\">"+(r.active?"Disable":"Enable")+"</button>";',
    '      h+="<button class=\\"btn btn-danger btn-sm\\" onclick=\\"delKey("+r.id+")\\">Del</button>";',
    '      h+="</td></tr>";',
    '    }',
    '    tb.innerHTML=h;',
    '  }).catch(function(e){toast(e.message,"#f85149");});',
    '}',
    '',
    'function createKey(){',
    '  var name=document.getElementById("keyName").value;',
    '  api("/admin/keys",{method:"POST",body:JSON.stringify({name:name})})',
    '  .then(function(d){document.getElementById("keyName").value="";cp(d.key);toast("Key created & copied!","#3fb950");loadKeys();})',
    '  .catch(function(e){toast(e.message,"#f85149");});',
    '}',
    '',
    'function togKey(id,active){api("/admin/keys/"+id,{method:"PATCH",body:JSON.stringify({active:!!active})}).then(function(){loadKeys();});}',
    '',
    'function delKey(id){if(!confirm("Delete this key?"))return;api("/admin/keys/"+id,{method:"DELETE"}).then(function(){toast("Deleted","#3fb950");loadKeys();});}',
    '',
    '// ── Models ──',
    'function loadModels(){',
    '  api("/admin/models").then(function(rows){',
    '    var tb=document.getElementById("mdlTbl");',
    '    if(!rows.length){tb.innerHTML="<tr><td colspan=\\"4\\" style=\\"text-align:center;color:var(--text3);padding:24px\\">No models.</td></tr>";return;}',
    '    var h="";',
    '    for(var i=0;i<rows.length;i++){',
    '      var r=rows[i];',
    '      h+="<tr>";',
    '      h+="<td class=\\"mono\\">"+esc(r.model_id)+"</td>";',
    '      h+="<td>"+esc(r.display_name||r.model_id)+"</td>";',
    '      h+="<td><span class=\\"badge "+(r.active?"badge-green":"badge-red")+"\\">"+(r.active?"Listed":"Unlisted")+"</span></td>";',
    '      h+="<td class=\\"actions\\">";',
    '      h+="<button class=\\"btn btn-secondary btn-sm\\" onclick=\\"togMdl("+r.id+","+(r.active?0:1)+")\\">"+(r.active?"Unlist":"List")+"</button>";',
    '      h+="<button class=\\"btn btn-danger btn-sm\\" onclick=\\"delMdl("+r.id+")\\">Del</button>";',
    '      h+="</td></tr>";',
    '    }',
    '    tb.innerHTML=h;',
    '  }).catch(function(e){toast(e.message,"#f85149");});',
    '}',
    '',
    'function addModel(){',
    '  var mid=document.getElementById("mdlId").value.trim();',
    '  var mname=document.getElementById("mdlName").value.trim();',
    '  if(!mid){toast("Model ID required","#f85149");return;}',
    '  api("/admin/models",{method:"POST",body:JSON.stringify({model_id:mid,display_name:mname})})',
    '  .then(function(){document.getElementById("mdlId").value="";document.getElementById("mdlName").value="";toast("Model added!","#3fb950");loadModels();})',
    '  .catch(function(e){toast(e.message,"#f85149");});',
    '}',
    '',
    'function togMdl(id,active){api("/admin/models/"+id,{method:"PATCH",body:JSON.stringify({active:!!active})}).then(function(){loadModels();});}',
    '',
    'function delMdl(id){if(!confirm("Remove this model?"))return;api("/admin/models/"+id,{method:"DELETE"}).then(function(){toast("Deleted","#3fb950");loadModels();});}',
    '',
    '// ── Sessions ──',
    'function loadSessions(){',
    '  api("/admin/conversations").then(function(rows){',
    '    var tb=document.getElementById("sessTbl");',
    '    if(!rows.length){tb.innerHTML="<tr><td colspan=\\"6\\" style=\\"text-align:center;color:var(--text3);padding:24px\\">No active sessions.</td></tr>";return;}',
    '    var h="";',
    '    for(var i=0;i<rows.length;i++){',
    '      var r=rows[i];',
    '      h+="<tr>";',
    '      h+="<td class=\\"mono\\" title=\\""+esc(r.conv_key)+"\\">"+esc(r.conv_key.slice(0,16))+"\\u2026</td>";',
    '      h+="<td>"+esc(r.account_label||"?")+" <span style=\\"color:var(--text3)\\">("+esc(r.user_id||"?")+")</span></td>";',
    '      h+="<td><span class=\\"badge badge-blue\\">"+esc(r.model||"?")+"</span></td>";',
    '      h+="<td>"+r.message_count+"</td>";',
    '      h+="<td style=\\"color:var(--text2)\\">"+timeAgo(r.last_used)+"</td>";',
    '      h+="<td style=\\"color:var(--text3)\\">"+timeAgo(r.created_at)+"</td>";',
    '      h+="</tr>";',
    '    }',
    '    tb.innerHTML=h;',
    '  }).catch(function(){});',
    '}',
    '',
    'function clearConvs(){',
    '  if(!confirm("Clear all sessions?"))return;',
    '  api("/admin/conversations",{method:"DELETE"}).then(function(){toast("Cleared","#3fb950");loadSessions();}).catch(function(e){toast(e.message,"#f85149");});',
    '}',
    '',
    '// ── Auto-login ──',
    'function tryAutoLogin(){',
    '  if(!token)return;',
    '  api("/admin/accounts").then(function(){',
    '    loggedIn=true;',
    '    document.getElementById("hInfo").textContent="Admin";',
    '    document.getElementById("hInfo").style.borderColor="#3fb950";',
    '    buildNav();sp("dashboard");',
    '  }).catch(function(){token="";localStorage.removeItem("m2a_token");});',
    '}',
    '',
    'if(token)tryAutoLogin();',
  ].join('\n');

  return '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<title>MiMo2API</title>\n<style>\n' + css + '\n</style>\n</head>\n<body>\n' + body + '\n<script>\n' + js + '\n<\/script>\n</body>\n</html>';
}
